# Site settings
title: Code Lilies
description: 'Code Lilies - Beautiful tricks from the swamp'
url: 'http://www.sbisinger.net/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'codelilies'

author:
  name: 'Stéphane Bisinger'
  email: stephane.bisinger@gmail.com
  twitter_username: SteBjoerne
  github_username:  Kjir
  facebook_username: ste.bis

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

gems:
    - 'jekyll-paginate'
    - 'jekyll-coffeescript'

kramdown:
  input: GFM
  hard_wrap: false


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
