baseurl = "https://www.sbisinger.ch/"
DefaultContentLanguage = "en"
title = "Code Lilies"
theme = "m10c"
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
# disqusShortname = "codelilies"

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Solutions to programming problems in the strive for elegance"
  logo = "images/profile.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = false
  socialShare = true
  author = "Stéphane Bisinger"
  description = """
  Hi, my name is Stéphane Bisinger.
  I write about functional programming, coding best practices, performance optimization and serverless architectures.
  I'm currently living in the beautiful city of Zürich, Switzerland.
  """
  [[params.social]]
    name = "github"
    url = "https://github.com/Kjir"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/SteBjoerne"
  [[params.social]]
    name = "stackoverflow"
    url = "https://www.stackoverflow.com/users/287030/kjir"
  [params.style]
    darkestColor = "#1e1b1c"
    darkColor = "#eef8ff"
    primaryColor = "#922802"
    lightColor = "#223127"
    lightestColor = "#2a7a92"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Stéphane Bisinger"
  website = "https://www.sbisinger.ch"
  email = "stephane@sbisinger.ch"
  github = "Kjir"
  gitlab = "Kjir"
  twitter = "SteBjoerne"
  linkedin = "stéphane-bisinger-30b922163"
  xing = "Stephane_Bisinger"
  stackoverflow = "users/287030/kjir"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "CV"
    url = "https://www.stackoverflow.com/story/stebis"
    weight = 3
