baseURL = "https://www.sbisinger.ch"
disablePathToLower = true
pygmentsuseclasses = true
pygmentCodeFences = true
languageCode = "en-us"
title = "Code Lilies"
disqusShortname = 'codelilies'
theme = "minimalist"
[params]
    site_author = "Stéphane Bisinger"
    site_description = "Solutions to programming problems in the strive for elegance"
    location = "Zürich"
    # Link custom assets relative to /static
    avatar = "images/profile.png"
    header_background = "images/editor.png"
    header_title = "Code Lilies"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "SteBjoerne"
    facebook  = "stephane.bis"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "Kjir"
    gplus     = ""
