baseurl = "https://www.sbisinger.ch/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Stéphane Bisinger"
title = "Code Lilies"
disqusshortname = "codelilies"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"
post = "/:year/:month/:day/:title/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Solutions to programming problems in the strive for elegance"
copyright = "Copyright © 2018 Stéphane Bisinger"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "images/profile.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "Kjir"
email = "stephane@sbisinger.ch"
linkedin = "john-example-aa80ue8è"
twitter = "SteBjoerne"
# social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = false
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
